# Python Libraries 1
# Numpy ![numpy.png](attachment:numpy.png)

In [ ]:
import numpy

In [ ]:
l=[1,2,3]
arr=numpy.array(l)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
import numpy as np

In [ ]:
np.array(l)

array([1, 2, 3])

In [ ]:
arr_1=np.array([1,2,3])

In [ ]:
arr_1

array([1, 2, 3])

In [ ]:
arr_1+1

array([2, 3, 4])

In [ ]:
arr_1*2

array([2, 4, 6])

In [ ]:
l_1=[1,2,3]
l_2=[2,3,4]
l_1+l_2

[1, 2, 3, 2, 3, 4]

In [ ]:
arr_1=np.array(l_1)
arr_2=np.array(l_2)

In [ ]:
arr_1+arr_2

array([3, 5, 7])

In [ ]:
arr_1.sum()

6

In [ ]:
#Indexing
arr_1[0]

1

In [ ]:
arr_1[2]

3

In [ ]:
for i in arr_1:
    print(i)

1
2
3


In [ ]:
arr_2D=np.array([[1,1],[2,1],[3,2]])

In [ ]:
arr_2D

array([[1, 1],
       [2, 1],
       [3, 2]])

In [ ]:
rand_array=np.random.random(size=[3,2])

In [ ]:
zero_array=np.zeros(shape=[3,2])
zero_array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
zero_array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
rand_array=np.random.random(size=[5,5])

In [ ]:
rand_array

array([[0.18756505, 0.1570576 , 0.83158817, 0.04431161, 0.35687993],
       [0.25323474, 0.9957606 , 0.52332026, 0.55185452, 0.28640817],
       [0.48285586, 0.45600856, 0.2291647 , 0.04733981, 0.18561521],
       [0.17458288, 0.97394082, 0.64476136, 0.84609033, 0.62073933],
       [0.43554784, 0.67062266, 0.47590727, 0.7638277 , 0.84893053]])

In [ ]:
rand_array[1,1]

0.9957605974017925

In [ ]:
rand_array[0:2,0:2]

array([[0.18756505, 0.1570576 ],
       [0.25323474, 0.9957606 ]])

In [ ]:
rand_array.sum(axis=1)

array([1.57740235, 2.61057829, 1.40098413, 3.26011472, 3.19483599])

In [ ]:
np.array([0.4924862 , 0.58400964, 0.42182289, 0.31476085, 0.26750594]).sum()

2.08058552

In [ ]:
rand_array*10

array([[1.87565045, 1.57057603, 8.31588169, 0.44311609, 3.56879926],
       [2.53234742, 9.95760597, 5.23320261, 5.51854515, 2.86408175],
       [4.82855858, 4.56008558, 2.29164698, 0.47339809, 1.85615207],
       [1.74582877, 9.73940817, 6.44761356, 8.46090334, 6.20739333],
       [4.35547839, 6.70622655, 4.75907274, 7.63827697, 8.48930526]])

In [ ]:
rand_array

array([[0.18756505, 0.1570576 , 0.83158817, 0.04431161, 0.35687993],
       [0.25323474, 0.9957606 , 0.52332026, 0.55185452, 0.28640817],
       [0.48285586, 0.45600856, 0.2291647 , 0.04733981, 0.18561521],
       [0.17458288, 0.97394082, 0.64476136, 0.84609033, 0.62073933],
       [0.43554784, 0.67062266, 0.47590727, 0.7638277 , 0.84893053]])

In [ ]:
rand_array=np.random.random(size=100)

In [ ]:
rand_array.sort()


In [ ]:
rand_array

array([0.00498686, 0.01843061, 0.02856003, 0.03770077, 0.03818092,
       0.0449142 , 0.04815441, 0.0484055 , 0.05160406, 0.06211547,
       0.06414577, 0.0748948 , 0.08886428, 0.08900885, 0.1151853 ,
       0.13055318, 0.1358873 , 0.1406211 , 0.14491263, 0.15761251,
       0.16211741, 0.16763832, 0.18404151, 0.18652002, 0.19100095,
       0.19642922, 0.19763387, 0.2016546 , 0.20486252, 0.2282631 ,
       0.2473255 , 0.27000365, 0.27384228, 0.28904529, 0.29864405,
       0.35905466, 0.36483036, 0.36725032, 0.37662261, 0.3877577 ,
       0.38978856, 0.39485752, 0.40025127, 0.40188842, 0.4180588 ,
       0.42295127, 0.4318669 , 0.43472349, 0.46877408, 0.49547251,
       0.50806082, 0.50968826, 0.52525902, 0.5370861 , 0.5429912 ,
       0.60669944, 0.61161987, 0.62183994, 0.62363728, 0.62450169,
       0.63431425, 0.64271917, 0.64393008, 0.65743728, 0.67944449,
       0.69111663, 0.69851822, 0.70730685, 0.7081073 , 0.71483617,
       0.71550699, 0.71922429, 0.72425065, 0.74387235, 0.74798

In [ ]:
for i in rand_array:
    print(i)

0.004986860587690711
0.018430606869119792
0.028560032000422675
0.03770077498876212
0.038180921395257306
0.04491419682752795
0.04815441134234433
0.04840549693595286
0.051604058226229155
0.06211547020045027
0.06414576831871677
0.07489479938357557
0.08886428148680414
0.08900885313770879
0.11518529849242709
0.13055317668168764
0.13588729525216048
0.14062109964278258
0.14491263085000727
0.1576125050838626
0.16211741060993512
0.16763831730034828
0.18404150913809703
0.18652001593927703
0.19100094652871236
0.19642921975257177
0.19763386519646708
0.20165459621927528
0.20486252125549664
0.22826309703185166
0.24732550186786684
0.27000364584702563
0.273842280827415
0.2890452851652666
0.2986440485659144
0.3590546626148432
0.36483035533094743
0.3672503237267529
0.3766226129738659
0.3877576959266029
0.3897885639492479
0.3948575236565727
0.4002512691289456
0.401888417785383
0.418058799116938
0.42295126884163936
0.4318668985106009
0.4347234929418955
0.4687740833111157
0.49547251031216333
0.508060822309

In [ ]:
# Exercises.

In [ ]:
x=np.linspace(0,10,100)
x.sum()

500.0

In [ ]:
#Calculate y=7x+2
y=(7*x)+2
y

array([ 2.        ,  2.70707071,  3.41414141,  4.12121212,  4.82828283,
        5.53535354,  6.24242424,  6.94949495,  7.65656566,  8.36363636,
        9.07070707,  9.77777778, 10.48484848, 11.19191919, 11.8989899 ,
       12.60606061, 13.31313131, 14.02020202, 14.72727273, 15.43434343,
       16.14141414, 16.84848485, 17.55555556, 18.26262626, 18.96969697,
       19.67676768, 20.38383838, 21.09090909, 21.7979798 , 22.50505051,
       23.21212121, 23.91919192, 24.62626263, 25.33333333, 26.04040404,
       26.74747475, 27.45454545, 28.16161616, 28.86868687, 29.57575758,
       30.28282828, 30.98989899, 31.6969697 , 32.4040404 , 33.11111111,
       33.81818182, 34.52525253, 35.23232323, 35.93939394, 36.64646465,
       37.35353535, 38.06060606, 38.76767677, 39.47474747, 40.18181818,
       40.88888889, 41.5959596 , 42.3030303 , 43.01010101, 43.71717172,
       44.42424242, 45.13131313, 45.83838384, 46.54545455, 47.25252525,
       47.95959596, 48.66666667, 49.37373737, 50.08080808, 50.78

In [ ]:
#Calculate y=x**2 for the first 10 elements
first_10=x[0:10]
y=first_10**2
y

array([0.        , 0.01020304, 0.04081216, 0.09182736, 0.16324865,
       0.25507601, 0.36730946, 0.49994898, 0.65299459, 0.82644628])

In [ ]:
x[2]*x[2]

0.040812162024283234

In [ ]:
#Define a 100 equally spaced points using linspace. And then another 100 random points. And then add x and y together
x=np.linspace(0,10,100)

y=np.random.random(size=100)


In [ ]:
#Add x and y together and save in z
z=x+y

In [ ]:
#Calculate the sum of of x,y and z and tell me which one is the largest

In [ ]:
#calcuate this largest number
largest=max(np.max(x),np.max(y),np.max(z))
print(largest)

10.96712153587457


In [ ]:
z

array([ 0.53786338,  0.15673984,  0.41644095,  0.99521408,  0.85760674,
        1.04564536,  0.82006796,  1.51460738,  0.91034795,  1.12076135,
        1.66904856,  1.6247293 ,  1.3854229 ,  1.65460289,  2.14193178,
        2.50426054,  2.42933489,  2.58684858,  2.04929413,  2.60260531,
        2.81302901,  2.41265387,  2.86240887,  2.39772986,  3.08698645,
        2.93993908,  3.36108146,  3.46833117,  3.19039688,  3.47163236,
        3.35319035,  3.29175487,  3.3627431 ,  3.95663947,  4.29903585,
        4.16725022,  4.61354453,  4.29017873,  4.44883823,  4.69017122,
        4.80143022,  4.7080398 ,  4.46661973,  4.66156421,  5.19585594,
        5.05645147,  5.16903059,  5.39682254,  5.27855398,  5.23236453,
        5.76857803,  5.94223712,  5.9921721 ,  5.70276146,  5.6693143 ,
        5.79272156,  6.60283973,  5.9447591 ,  6.44621808,  6.18859156,
        6.62039863,  6.87427741,  7.10300048,  6.79040407,  7.17774202,
        6.72705127,  7.32377862,  6.94553277,  7.02578987,  7.25

In [ ]:
print(x.sum())
print(y.sum())
print(z.sum())

500.0
50.48122057753568
550.4812205775355
